/*Insertar Tratamientos*/
INSERT INTO `tratamientos` (`nombreTratamiento`, `descripcionTratamiento`, `precio`) VALUES
('Blanqueamiento dental', 'Consiste en quitar todas las manchas dentales que puedan tener los dientes, ya sean provocadas por causas naturales o por factores externos como la cafeína o la nicotina.', '50.00'),
('Implantes dentales', 'Los materiales que se utilizan para llevar a cabo este tratamiento dental son biocompatibles con el resto de nuestra boca, por ello lo que pretendemos hacer es una implantación natural y que apenas se note para que el paciente se sienta a gusto y apenas sienta que lleva implantes dentales.', 900.00),
('Férula dental', 'ipo de tratamiento dental  que a pesar de ser rígido y duro permiten una gran movilidad de la mandíbula.El fin principal de estas férulas dentales es conseguir una adaptación perfecta entre los dientes y tu boca de tal forma que evitamos cualquier sobrecarga que pueda sufrir nuestro cliente.', 300.00),
('Ortodoncia brackets', 'Este tipo de tratamiento bucal lo utilizamos para corregir los problemas de la mordida, de tal manera  que tiene como principal objetivo alinear los dientes y la mandíbula. La ortodoncia con brackets se puede dar tanto en niños como en adultos adultos, dependiendo del origen del problema.', 1500.90),
('Ortodoncia invisible', 'Se utilizan brakets transparentes o invisibles de tal manera que queda mucho más estético a la hora de lucir tu sonrisa. Se puede considerar un tipo de tratamiento dental estético que te proporcionara un bienestar favorable.Este tipo de ortodonciadental puede corregir problemas como dientes montados, separación de dientes, mordida cruzada o sobre-mordida.',2500.00),
('Prótesis dental removible', 'Las prótesis dentales removibles cuentan con una serie de ventajas, entre ellas tienen gran flexibilidad lo que permite una mejor adaptación a la cavidad bucal y también se pueden utilizar cuando queremos sustituir determinadas piezas, nuestro paciente no tiene porque a haber perdido todas las piezas, aunque en este caso, optar por este tipo de tratamiento dental sería el más acertado.', 1500.00),
('Tratamiento periodontal', 'El tratamiento periodontal es fantástico para la inflamación de encías. Este tipo de problemas, de inflamación de encías o encías que sangran, tiene su solución en este tratamiento dental, ya que este tipo de patologías solo podremos evitarlas con tratamientos desinflamantes de encías.',100.00),
('Carillas de porcelana o zirconio', 'Este tipo de tratamiento dental, también relacionado con la estética dental, consiste en el desgaste de la cara vestibular de los dientes, pudiendo abarcar caninos o solamente los incisivos, para tras tomar medidas exactas de la anatomía de las piezas dentales, mandar a fabricar unas finas capas de porcelana o zirconio, que serán hechas a medida y se pegarán al diente con una resina especial para carillas. Tienen una gran demanda y el efecto visual es inmejorable, siendo una solución perfecta para el diseño de sonrisa en caso de pacientes con dientes empastados, bordes incisales partidos, diferentes tamaños de dientes, etc. La ventaja de las carillas bucales es que tienen un alto componente natural y estético que hace que apenas se note que las llevas.',300.00);


/*Insertar Servicio*/
INSERT INTO `pruebas`(`nombrePrueba`, `descripcionPrueba`, `precio`) VALUES 
('Ortopantomografía','También llamada radiografía dental panorámica, es el tipo de radiografía dental más común. De hecho, lo más corriente es que se efectúe en la primera visita del paciente a la clínica, durante su revisión general. Con un aparato de rayos X, se toma una imagen completa de la boca del paciente. Gracias a las ortopantomografías, los dentistas pueden identificar patologías y anomalías en las raíces dentales o en dientes incluidos: que no han erupcionado de la encía. También puede valorar el estado de las articulaciones y sus maxilares.',50.00),
('TAC Dental','el TAC Dental toma cientos de imágenes desde diferentes ángulos de la boca del paciente. Estas radiografías son enviadas a un ordenador, que genera una imagen virtual en 3 dimensiones de la boca del paciente. A partir de ella, el dentista puede efectuar secciones para observar la anatomía de la boca del paciente en puntos muy concretos y estudiar la boca del paciente con un detalle que, sin esta técnica, sería impensable.',80.00),
('Cefalometría','Es un tipo de radiografía que, en el ámbito odontológico, prácticamente solo se usa en los estudios previos a una ortodoncia. Permite conocer el estado general de los huesos del cráneo y las proporciones entre ellos, para detectar los problemas esqueléticos que pueden hacer necesario uno de estos tratamientos.',110.50),
('Radiografías periapical','Normalmente, se usan para obtener una imagen completa de la estructura de uno o dos dientes: raíces y coronas.',200.00),
('Radiografía de aleta/mordida','La placa se coloca a lo largo de la mordida del paciente, para obtener una imagen completa de las coronas dentales del paciente. Se usan especialmente en los casos de caries interproximal.',73.68;